---
services:
  keycloak-app:
    command: start-dev
    container_name: keycloak-app
    depends_on:
      - keycloak-mysql
    environment:
      KC_DB: mysql
      KC_DB_PASSWORD: MyKeycloakMySQLPassword
      KC_DB_URL: jdbc:mysql://keycloak-mysql:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_HEALTH_ENABLED: true
      KC_HOSTNAME: gentoo.hxp.lan
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    expose:
      - '8080'
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - '8080:8080'
  keycloak-mysql:
    container_name: keycloak-mysql
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_PASSWORD: MyKeycloakMySQLPassword
      MYSQL_ROOT_PASSWORD: MyRootPassword
      MYSQL_USER: keycloak
    expose:
      - '3306'
    image: mysql:8.0.37-debian
    volumes:
      - keycloak-mysql:/var/lib/mysql
  onlyoffice-docs:
    build: ./onlyoffice-docs
    container_name: onlyoffice-docs
    depends_on:
      - onlyoffice-redis
      - onlyoffice-rabbitmq
      - onlyoffice-postgres
    expose:
      - '8000'
    image: hxp.plus/onlyoffice/onlyoffice-docs:v20240611
    volumes:
      - onlyoffice-cache:/var/lib/onlyoffice
      - ./onlyoffice-docs/production-linux.json:/var/www/onlyoffice/documentserver/server/Common/config/production-linux.json
  onlyoffice-nginx:
    container_name: onlyoffice-nginx
    depends_on:
      - onlyoffice-docs
    expose:
      - '80'
    image: docker.io/library/nginx:1.27.0-alpine3.19
    ports:
      - '8081:80'
    volumes:
      - ./onlyoffice-nginx/nginx.conf:/etc/nginx/nginx.conf
  onlyoffice-postgres:
    container_name: onlyoffice-postgresql
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_PASSWORD=onlyoffice
    expose:
      - '5432'
    image: docker.io/library/postgres:13.15-alpine3.20
    volumes:
      - ./onlyoffice-postgres/createdb.sql:/root/createdb.sql
      - onlyoffice-postgres:/var/lib/postgresql
  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    expose:
      - '5672'
    image: docker.io/library/rabbitmq:3.13.3-alpine
  onlyoffice-redis:
    container_name: onlyoffice-redis
    expose:
      - '6379'
    image: docker.io/library/redis:7.4-rc1-alpine3.20
volumes:
  keycloak-mysql:
    name: keycloak-mysql
    driver: local
  onlyoffice-cache:
    name: onlyoffice-cache
    driver: local
  onlyoffice-postgres:
    name: onlyoffice-postgres
    driver: local